project_id = "pxhabmwihhxwznmuvgrb"

[functions.admin-auth]
verify_jwt = false

[functions.admin-restaurant]
verify_jwt = false

[functions.admin-categories]
verify_jwt = false

[functions.admin-products]
verify_jwt = false

[functions.public-menu]
verify_jwt = false