// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pxhabmwihhxwznmuvgrb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB4aGFibXdpaGh4d3pubXV2Z3JiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg4MTc3OTgsImV4cCI6MjA3NDM5Mzc5OH0.Vx5TS8IiPEOdW6VY19-ItsiuI9MmwkRjR5UgmdpxlBA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});